
modLoader="javafml"

loaderVersion="[32,)"

issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="unusedassets" 

version="Pre-Build" 

displayName="Unused Assets" 

updateJSONURL="http://myurl.me/"

displayURL="http://example.com/"

logoFile="examplemod.png"

credits="Credits here" 

authors="Gizmo"

description='''
A work-in-progress mod that adds all blocks, items, entites, and such to the game that were removed, changed, or never used. 
'''

[[dependencies.unusedassets]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    side="BOTH"

[[dependencies.unusedassets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"

	
